import Foundation

/// The single place a selected model ID becomes something the generation
/// backend can actually run.
///
/// Before this existed, `ModelRegistry` (which owns policy, licensing and
/// model definitions) and
/// `LTXModelCatalog` (which owns the repositories the MLX backend is known to
/// run) were consulted independently: four model pickers offered
/// `ModelRegistry.selectableModels()`, while `LTXBridge` resolved the chosen
/// ID through `LTXModelCatalog.resolvedModel(id:)`, which silently returns the
/// default model for an unknown ID. Selecting a registry-only model therefore
/// produced a video generated by a *different* checkpoint than the one asked
/// for, with no error and no diagnostic trace.
///
/// Resolution is intentionally table-driven — a lookup in the runnable
/// catalog, never a match on substrings of the model name — so adding a model
/// is a registry entry, not a new branch.
///
/// This is also the seam where a second generation backend would attach: today
/// every runnable profile maps to the LTX/MLX backend, and a future family
/// would resolve to its own backend here without the Director, Storyboard,
/// Auto Movie or Production Queue layers changing.
enum GenerationModelResolver {

    /// Why a model the user can see cannot currently be generated with.
    enum UnsupportedReason: Equatable {
        /// Registered for policy/licensing purposes, but the installed backend
        /// has no verified way to run it.
        case notRunnableOnInstalledBackend(modelID: String, displayName: String, detail: String)
        /// Not a model this build knows at all.
        case unknownModel(modelID: String)

        var userMessage: String {
            switch self {
            case .notRunnableOnInstalledBackend(_, let displayName, let detail):
                return "\(displayName) cannot be generated with by this build. \(detail)"
            case .unknownModel(let modelID):
                return "The selected video model (\(modelID)) is not available in this build. Choose a model in Preferences → General."
            }
        }
    }

    /// A model plus the runtime that will actually execute it.
    struct RunnableModel: Equatable {
        let model: LTXModel
        let backend: GenerationBackendKind
    }

    enum Resolution: Equatable {
        /// A model an installed backend is known to run.
        case runnable(RunnableModel)
        case unsupported(UnsupportedReason)
    }

    /// Resolves without falling back to a different checkpoint. A caller that
    /// gets `.unsupported` must surface it, never substitute another model.
    static func resolve(
        modelID: String?,
        registry: ModelRegistry = .shared,
        userDefaults: UserDefaults = .standard
    ) -> Resolution {
        guard let modelID, !modelID.isEmpty else {
            // No selection at all keeps the historical default, which is what
            // every project written before model selection existed expects.
            return .runnable(RunnableModel(model: LTXModelCatalog.defaultModel,
                                           backend: .mlxVideoWithAudio))
        }
        if let runnable = LTXModelCatalog.model(id: modelID) {
            return .runnable(RunnableModel(model: runnable, backend: .mlxVideoWithAudio))
        }
        if modelID == MiniMaxH3Configuration.modelID,
           let descriptor = registry.descriptor(id: modelID) {
            let runnable = LTXModel(
                id: descriptor.id,
                repo: descriptor.repository,
                displayName: descriptor.displayName,
                downloadSize: descriptor.estimatedModelSizeGB.map { "~\(Int($0))GB" } ?? "local",
                supportsBuiltInAudio: descriptor.capabilities.synchronizedAudio,
                qualityWarning: MiniMaxH3ProductPolicy.modelDescription,
                recommendedStepsLower: 8,
                recommendedStepsUpper: 8,
                tips: descriptor.runtime.verificationNotes)
            return .runnable(RunnableModel(model: runnable, backend: .minimaxH3))
        }
        if let runnable = LTX25ModelCatalog.model(id: modelID) {
            return .runnable(RunnableModel(model: runnable, backend: .ltx2MLX))
        }
        if let runnable = LTX2MLXModelCatalog.model(id: modelID) {
            return .runnable(RunnableModel(model: runnable, backend: .ltx2MLX))
        }
        if let profile = CustomModelProfileStore.profile(forModelID: modelID, userDefaults: userDefaults) {
            let customModel = LTXModel(
                id: profile.modelID,
                repo: profile.displayName,
                displayName: profile.displayName,
                downloadSize: "~14GB",
                supportsBuiltInAudio: true,
                qualityWarning: nil,
                recommendedStepsLower: 8,
                recommendedStepsUpper: 8,
                tips: "Custom model profile: \(profile.displayName)"
            )
            return .runnable(RunnableModel(model: customModel, backend: .ltx2MLX))
        }
        if let descriptor = registry.descriptor(id: modelID) {
            return .unsupported(.notRunnableOnInstalledBackend(
                modelID: modelID,
                displayName: descriptor.displayName,
                detail: descriptor.runtime.verificationNotes
                    ?? "The installed generation backend has not verified this model."))
        }
        return .unsupported(.unknownModel(modelID: modelID))
    }

    /// True when a selected model can actually be generated with. UI uses this
    /// to explain a selection instead of letting it fail at generation time.
    static func isRunnable(modelID: String?, registry: ModelRegistry = .shared) -> Bool {
        if case .runnable = resolve(modelID: modelID, registry: registry) { return true }
        return false
    }

    /// The runtime a model routes to, or nil when it cannot be generated with.
    /// Never guesses: an unrunnable model has no backend rather than the
    /// default one, which is what keeps a failed custom model request from being
    /// quietly served by the LTX-2.3 backend.
    static func backend(for modelID: String?, registry: ModelRegistry = .shared) -> GenerationBackendKind? {
        if case .runnable(let runnable) = resolve(modelID: modelID, registry: registry) {
            return runnable.backend
        }
        return nil
    }
}
